# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27fcab9f5c2b9104facbb79e195603089f435898c0b4e352e283d002d68eaa553495ef2602cd462c094a90928d36935e83779605600977effceea7a0fce3a164

test:
  secret_key_base: 3e506b6d1069321b818732c913dbf6ffe3b03e1282ec28d2dacfe3b0925ba20617c72fc9a7961055e873bfa66b059ad900c40691aa864da9e88198a88fcdfcc1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
