# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e19ece511f67d8d5b35f4c320d0b2410aa88852b0d3321b4762fa401c9049fba09105946bc9c4d106815acd9b844b0988653c779b8e4bbcf6187263829dc101

test:
  secret_key_base: acd74736a130e05cc32ee8a621b391ec22b496f6bb3768051a3798c7896ab220b8d1259aab1f4ee2d43622daf702fcdc4353353bf762c0503b88801e56230907

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
